import React from 'react';
import { Cpu, X } from 'lucide-react';

const MockInterviewModal = ({
  isOpen,
  onClose,
  interviewLoading,
  activeInterview,
  interviewAnswers,
  setInterviewAnswers,
  currentQuestionIdx,
  setCurrentQuestionIdx,
  handleAnswerSubmit,
  submittingAnswers,
  interviewResult
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-md flex items-center justify-center p-4 z-50 animate-fade-in">
      <div className="bg-white border border-purple-100 w-full max-w-2xl rounded-3xl p-6 flex flex-col gap-4 shadow-2xl relative overflow-hidden">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <Cpu className="w-5 h-5 text-purple-600 animate-spin-slow" />
            <div>
              <h3 className="font-extrabold text-sm text-slate-800 uppercase tracking-wider">AI Mock Coach Simulator</h3>
              {activeInterview && (
                <span className="text-[10px] text-purple-600 font-bold">
                  {activeInterview.job?.companyName || 'Corporate Target'} • Practice Module
                </span>
              )}
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 bg-slate-100 p-1 rounded-lg transition-all"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Main Interactive Stage */}
        {interviewLoading ? (
          <div className="py-24 flex flex-col items-center justify-center gap-3">
            <span className="w-8 h-8 border-3 border-slate-200 border-t-purple-600 rounded-full animate-spin"></span>
            <p className="text-xs text-slate-400 uppercase tracking-wider font-extrabold animate-pulse">Gemini preparing interview canvas...</p>
          </div>
        ) : interviewResult ? (
          /* Scorecard screen */
          <div className="space-y-5 py-4 flex flex-col items-center">
            <div className="relative w-28 h-28 flex items-center justify-center rounded-full bg-slate-50 border-2 border-emerald-500 shadow-lg">
              <span className="text-3xl font-black text-slate-800">{interviewResult.score}%</span>
              <span className="absolute bottom-3 text-[9px] text-emerald-650 uppercase font-black tracking-widest">Score</span>
            </div>
            
            <div className="text-center space-y-1">
              <h4 className="font-extrabold text-slate-800 text-sm">Evaluation Complete!</h4>
              <p className="text-xs text-slate-500">Structured recommendations generated by Gemini AI</p>
            </div>

            <div className="w-full p-4 rounded-2xl bg-slate-50 border border-slate-200 text-left space-y-2">
              <span className="text-[10px] text-purple-605 font-black uppercase tracking-wider">Coach Feedback</span>
              <p className="text-xs text-slate-700 leading-relaxed whitespace-pre-wrap">{interviewResult.feedback}</p>
            </div>

            <button
              onClick={onClose}
              className="px-6 py-2.5 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-xl text-xs uppercase tracking-wider transition-all"
            >
              Acknowledge & Close
            </button>
          </div>
        ) : activeInterview ? (
          /* Active Simulation Terminal */
          <div className="space-y-4 text-left">
            {/* Progress bar */}
            <div className="w-full flex justify-between items-center text-[10px] text-slate-500">
              <span>Question {currentQuestionIdx + 1} of 3</span>
              <span className="font-extrabold text-purple-600">{Math.round(((currentQuestionIdx + 1)/3)*100)}% Complete</span>
            </div>
            <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
              <div 
                className="h-full bg-gradient-to-r from-purple-500 to-indigo-500 transition-all duration-300"
                style={{ width: `${((currentQuestionIdx + 1)/3)*100}%` }}
              ></div>
            </div>

            {/* Question panel & Answer options */}
            {(() => {
              const currentQuestionRaw = activeInterview.questions[currentQuestionIdx];
              let currentQuestionObj = { question: currentQuestionRaw, options: [] };
              if (currentQuestionRaw) {
                try {
                  currentQuestionObj = JSON.parse(currentQuestionRaw);
                } catch (e) {
                  currentQuestionObj = { question: currentQuestionRaw, options: [] };
                }
              }

              return (
                <>
                  <div className="p-4 rounded-2xl bg-purple-50/50 border border-purple-100 min-h-[90px] flex items-center">
                    <p className="text-xs text-slate-800 font-bold leading-relaxed">
                      {currentQuestionObj.question}
                    </p>
                  </div>

                  {/* Answer selection */}
                  <div className="space-y-2">
                    {currentQuestionObj.options && currentQuestionObj.options.length > 0 ? (
                      <div className="grid grid-cols-1 gap-2.5">
                        {currentQuestionObj.options.map((option, idx) => {
                          const optionLetter = String.fromCharCode(65 + idx); // A, B, C, D
                          const isSelected = interviewAnswers[currentQuestionIdx] === optionLetter;
                          return (
                            <button
                              key={idx}
                              type="button"
                              onClick={() => {
                                const updated = [...interviewAnswers];
                                updated[currentQuestionIdx] = optionLetter;
                                setInterviewAnswers(updated);
                              }}
                              className={`w-full text-left p-3.5 rounded-2xl border transition-all flex items-center gap-3.5 ${
                                isSelected
                                  ? 'bg-purple-50/70 border-purple-550 ring-2 ring-purple-500/10 text-purple-950 font-semibold'
                                  : 'bg-white border-slate-200 hover:border-purple-300 text-slate-700 font-medium hover:bg-slate-50/30'
                              }`}
                            >
                              <div className={`w-7 h-7 rounded-full flex items-center justify-center font-extrabold text-[11px] shrink-0 transition-all ${
                                isSelected
                                  ? 'bg-purple-600 text-white shadow-md'
                                  : 'bg-slate-100 text-slate-550'
                              }`}>
                                {optionLetter}
                              </div>
                              <span className="text-[11px] leading-relaxed">{option}</span>
                            </button>
                          );
                        })}
                      </div>
                    ) : (
                      <div className="space-y-1">
                        <label className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block">Your Response</label>
                        <textarea
                          rows="6"
                          value={interviewAnswers[currentQuestionIdx]}
                          onChange={(e) => {
                            const updated = [...interviewAnswers];
                            updated[currentQuestionIdx] = e.target.value;
                            setInterviewAnswers(updated);
                          }}
                          placeholder="Structure your answer clearly, including relevant coding syntax, system architectures, or examples where applicable..."
                          className="w-full px-4 py-2.5 rounded-xl bg-slate-50 border border-slate-200 focus:border-purple-500 focus:ring-1 focus:ring-purple-500 text-slate-800 text-xs transition-all outline-none font-medium resize-none leading-relaxed"
                        />
                      </div>
                    )}
                  </div>
                </>
              );
            })()}

            {/* Actions */}
            <div className="flex justify-between items-center pt-2">
              <button
                disabled={currentQuestionIdx === 0}
                onClick={() => setCurrentQuestionIdx(prev => prev - 1)}
                className="px-4 py-2 bg-slate-100 hover:bg-slate-200 disabled:opacity-30 text-slate-550 font-semibold rounded-lg text-xs transition-all"
              >
                Back
              </button>
              
              {currentQuestionIdx < 2 ? (
                <button
                  onClick={() => setCurrentQuestionIdx(prev => prev + 1)}
                  className="px-5 py-2 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-lg text-xs uppercase tracking-wider transition-all"
                >
                  Next Question
                </button>
              ) : (
                <button
                  onClick={handleAnswerSubmit}
                  disabled={submittingAnswers}
                  className="px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-lg text-xs uppercase tracking-wider transition-all flex items-center gap-1 shadow-md"
                >
                  {submittingAnswers ? 'Evaluating...' : 'Submit Answers'}
                </button>
              )}
            </div>
          </div>
        ) : (
          <div className="py-16 text-center text-slate-400 italic text-xs">
            Failed to configure practice module.
          </div>
        )}
      </div>
    </div>
  );
};

export default MockInterviewModal;
